config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :sales_orders
end
 

app/models/sales_order.rb
class SalesOrder < ActiveRecord::Base
end

app/controllers/sales_orders_controller.rb
class SalesOrdersController < ApplicationController
require 'csv'

  def index
    @sosss = SalesOrder.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"soss-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end
  
  def show
    @soss = SalesOrder.find(params[:id])

        respond_to do |format|
        format.html
        format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"soss-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def new
    @soss = SalesOrder.new
  end

  def create
    @soss = SalesOrder.new(soss_params)
    if @soss.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @soss
    else
      render 'new'
    end
  end

  def edit
    @soss = SalesOrder.find(params[:id])
  end

  def update
    @soss = SalesOrder.find(params[:id])
    if @soss.update_attributes(soss_params)
      flash[:success] = "Profile updated"
      redirect_to @soss
    else
      render 'edit'
    end
  end


  def correct_user
    @soss = SalesOrder.find(params[:id])
    redirect_to(root_url) unless current_user?(@soss)
  end
  private

  def soss_params
    params.require(:sales_order).permit(:due_date, :bill_to, :requestor_name, :title, :address, :email, :origin_port, :dest_port, :mode, :service_level, :shipper_name, :shipper_address, :importer_of_record, :customs_origin_broker, :customs_dest_broker, :origin_airport, :actual_weight, :uom, :pcs, :dimensions_length, :dimensions_width, :dimensions_height, :chargeable_weight)
  end
end

app/helpers/sales_orders_helper.rb
module SalesOrdersHelper
end

app/views/sales_orders/_sales_order.erb
<%= link_to "#{sales_order.due_date}", sales_order %> <br>

app/views/sales_orders/edit.html.erb
<% provide(:title, "Edit Soss") %>
<h1>Update SOSS</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@soss) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :due_date %>
      <%= f.text_field :due_date, class: 'form-control' %>
      <%= f.label :bill_to %>
      <%= f.text_field :bill_to, class: 'form-control' %>
      <%= f.label :requestor_name %>
      <%= f.text_field :requestor_name, class: 'form-control' %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.label :origin_port %>
      <%= f.text_field :origin_port, class: 'form-control' %>
      <%= f.label :dest_port %>
      <%= f.text_field :dest_port, class: 'form-control' %>
      <%= f.label :mode %>
      <%= f.text_field :mode, class: 'form-control' %>
      <%= f.label :service_level %>
      <%= f.text_field :service_level, class: 'form-control' %>
      <%= f.label :shipper_name %>
      <%= f.text_field :shipper_name, class: 'form-control' %>
      <%= f.label :shipper_address %>
      <%= f.text_field :shipper_address, class: 'form-control' %>
      <%= f.label :importer_of_record %>
      <%= f.text_field :importer_of_record, class: 'form-control' %>
      <%= f.label :customs_origin_broker %>
      <%= f.text_field :customs_origin_broker, class: 'form-control' %>
      <%= f.label :customs_dest_broker %>
      <%= f.text_field :customs_dest_broker, class: 'form-control' %>
      <%= f.label :origin_airport %>
      <%= f.text_field :origin_airport, class: 'form-control' %>
      <%= f.label :actual_weight %>
      <%= f.text_field :actual_weight, class: 'form-control' %>
      <%= f.label :uom %>
      <%= f.text_field :uom, class: 'form-control' %>
      <%= f.label :pcs %>
      <%= f.text_field :pcs, class: 'form-control' %>
      <%= f.label :dimensions_length %>
      <%= f.text_field :dimensions_length, class: 'form-control' %>
      <%= f.label :dimensions_width %>
      <%= f.text_field :dimensions_width, class: 'form-control' %>
      <%= f.label :dimensions_height %>
      <%= f.text_field :dimensions_height, class: 'form-control' %>
      <%= f.label :chargeable_weight %>
      <%= f.text_field :chargeable_weight, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/sales_orders/index.csv.erb
<%- headers = ['due_date', 'bill_to', 'requestor_name', 'title', 'address', 'email', 'origin_port', 'mode', 'service_level', 'shipper_name', 'shipper_address', 'importer_of_record', 'customs_origin_broker', 'customs_dest_broker', 'origin_airport', 'actual_weight', 'uom', 'pcs', 'dimensions_length', 'dimensions_width', 'dimensions_height', 'chargeable_weight' ] -%>
<%= CSV.generate_line headers %>
<%- @sosss.each do |soss| -%>
  <%= CSV.generate_line([soss.due_date, soss.bill_to, soss.requestor_name, soss.title, soss.address, soss.email, soss.origin_port, soss.mode, soss.service_level, soss.shipper_name, soss.shipper_address, soss.importer_of_record, soss.customs_origin_broker, soss.customs_dest_broker, soss.origin_airport, soss.actual_weight, soss.uom, soss.pcs, soss.dimensions_length, soss.dimensions_width, soss.dimensions_height, soss.chargeable_weight]) %>
<%- end -%>

app/views/sales_orders/index.html.erb
<% provide(:title, 'All lists') %>
<h1>All lists</h1>


<ul class="users">
  <%= render @sosss %>
</ul>

<%= link_to 'Download CSV list', sales_orders_path(format: :csv) %>

app/views/sales_orders/new.html.erb
<% provide(:title, 'New Sales Order') %>
<h1>New Sales Order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @soss, url: {action: "create"} do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :due_date %>
      <%= f.text_field :due_date, class: 'form-control' %>
      <%= f.label :bill_to %>
      <%= f.text_field :bill_to, class: 'form-control' %>
      <%= f.label :requestor_name %>
      <%= f.text_field :requestor_name, class: 'form-control' %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.label :origin_port %>
      <%= f.text_field :origin_port, class: 'form-control' %>
      <%= f.label :mode %>
      <%= f.text_field :mode, class: 'form-control' %>
      <%= f.label :service_level %>
      <%= f.text_field :service_level, class: 'form-control' %>
      <%= f.label :shipper_name %>
      <%= f.text_field :shipper_name, class: 'form-control' %>
      <%= f.label :shipper_address %>
      <%= f.text_field :shipper_address, class: 'form-control' %>
      <%= f.label :importer_of_record %>
      <%= f.text_field :importer_of_record, class: 'form-control' %>
      <%= f.label :customs_origin_broker %>
      <%= f.text_field :customs_origin_broker, class: 'form-control' %>
      <%= f.label :customs_dest_broker %>
      <%= f.text_field :customs_dest_broker, class: 'form-control' %>
      <%= f.label :origin_airport %>
      <%= f.text_field :origin_airport, class: 'form-control' %>
      <%= f.label :actual_weight %>
      <%= f.text_field :actual_weight, class: 'form-control' %>
      <%= f.label :uom %>
      <%= f.text_field :uom, class: 'form-control' %>
      <%= f.label :pcs %>
      <%= f.text_field :pcs, class: 'form-control' %>
      <%= f.label :dimensions_length %>
      <%= f.text_field :dimensions_length, class: 'form-control' %>
      <%= f.label :dimensions_width %>
      <%= f.text_field :dimensions_width, class: 'form-control' %>
      <%= f.label :dimensions_height %>
      <%= f.text_field :dimensions_height, class: 'form-control' %>
      <%= f.label :chargeable_weight %>
      <%= f.text_field :chargeable_weight, class: 'form-control' %>
      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/sales_orders/show.csv.erb
<%- headers = ['due_date', 'bill_to', 'requestor_name', 'title', 'address', 'email', 'origin_port', 'mode', 'service_level', 'shipper_name', 'shipper_address', 'importer_of_record', 'customs_origin_broker', 'customs_dest_broker', 'origin_airport', 'actual_weight', 'uom', 'pcs', 'dimensions_length', 'dimensions_width', 'dimensions_height', 'chargeable_weight' ] -%>
<%= CSV.generate_line headers %>
<%- soss = @soss -%>
  <%= CSV.generate_line([soss.due_date, soss.bill_to, soss.requestor_name, soss.title, soss.address, soss.email, soss.origin_port, soss.mode, soss.service_level, soss.shipper_name, soss.shipper_address, soss.importer_of_record, soss.customs_origin_broker, soss.customs_dest_broker, soss.origin_airport, soss.actual_weight, soss.uom, soss.pcs, soss.dimensions_length, soss.dimensions_width, soss.dimensions_height, soss.chargeable_weight]) %>

app/views/sales_orders/show.html.erb
due_date:               <strong><%= @soss.due_date %> </strong><br>
bill_to:                <strong><%= @soss.bill_to %> </strong><br>
requestor_name:         <strong><%= @soss.requestor_name %> </strong><br>
title:                  <strong><%= @soss.title %> </strong><br>
address:                <strong><%= @soss.address %> </strong><br>
email:                  <strong><%= @soss.email %> </strong><br>
origin_port:            <strong><%= @soss.origin_port %> </strong><br>
mode:                   <strong><%= @soss.mode %> </strong><br>
service_level:          <strong><%= @soss.service_level %> </strong><br>
shipper_name:           <strong><%= @soss.shipper_name %> </strong><br>
shipper_address:        <strong><%= @soss.shipper_address %> </strong><br>
importer_of_record:     <strong><%= @soss.importer_of_record %> </strong><br>
customs_origin_broker:  <strong><%= @soss.customs_origin_broker %> </strong><br>
customs_dest_broker:    <strong><%= @soss.customs_dest_broker %> </strong><br>
origin_airport:         <strong><%= @soss.origin_airport %> </strong><br>
actual_weight:          <strong><%= @soss.actual_weight %> </strong><br>
uom:                    <strong><%= @soss.uom %> </strong><br>
pcs:                    <strong><%= @soss.pcs %> </strong><br>
dimensions_length:      <strong><%= @soss.dimensions_length %> </strong><br>
dimensions_width:       <strong><%= @soss.dimensions_width %> </strong><br>
dimensions_height:      <strong><%= @soss.dimensions_height %> </strong><br>
chargeable_weight:      <strong><%= @soss.chargeable_weight %> </strong><br>
<br><br>
<%= link_to "edit", edit_sales_order_path, class: "btn btn-warning"%>

<%= link_to 'Download CSV list', sales_order_path(format: :csv) %>