config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :sales_orders
end
 

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="links">
   <!--   Contact /
     Donate /
     Suggest /
     Terms of Use  -->
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <%= link_to "Wisht!", root_path %>
  </div>
  <div class="navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right navbar-icons">
      <% if logged_in? %>
        <li>
            <%= link_to "Users", users_path %></span>
        </li>
        <li>
            <%= link_to "Profile", current_user %></span>
        </li>
        <li>
           <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
        <li>
           <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
      <% else %>
        <li>
          <a href="#">
            <span class="ss-settings"></span><span class="hidden-lg"><%= link_to "Log in", login_path %></span>
          </a>
        </li>
        <% end %>
    </ul>
  </div>
  <% if logged_in? %>
  <div class="welcome-tag">
     <p class="navbar-text navbar-right">Welcome, <a href="#" class="navbar-link"><%=current_user.name%></a></p>
  </div>
  <% end %>
</nav>

app/views/layouts/_header_loggedout.html.erb
<nav class="navbar navbar-inverse" role="navigation">

  <div class="navbar-collapse">
    <ul class="nav navbar-nav navbar-left navbar-icons">

    </ul>


    <ul class="nav navbar-nav navbar-right navbar-icons">
        <li>
          <h4 class="login"><%= link_to "Log in", login_path%></h4>
        </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Group-F</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user != nil %>
<%= render 'layouts/header' %>
<% else %>
<%= render 'layouts/header_loggedout' %>
<% end %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="yield">

        <% link_to 'Download CSV list', sales_orders_path(format: :csv) %>
      <%= yield %>
      </div>
      <%= render 'layouts/footer' %>

    </div>

</body>
</html>